[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    mikalhart/TinyGPSPlus@^1.0.3
    electroniccats/MPU6050@^0.8.0
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.7
    miguelbalboa/MFRC522@^1.4.11
    espressif/ESP32 BLE Arduino@^1.0.1

build_flags = 
    -I include/
    -D CONFIG_ESPTOOLPY_FLASHMODE_QIO
    -D CONFIG_ESPTOOLPY_FLASHFREQ_80M
    -D CONFIG_ESPTOOLPY_FLASHSIZE_4MB

upload_speed = 921600
monitor_filters = esp32_exception_decoder

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
lib_deps = 
    mikalhart/TinyGPSPlus@^1.0.3
    electroniccats/MPU6050@^0.8.0
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.7
    miguelbalboa/MFRC522@^1.4.11
    espressif/ESP32 BLE Arduino@^1.0.1
