#!/bin/bash

echo "🖨️ URBAN LAB - SISTEMA DI STAMPA 3D"
echo "===================================="
echo ""
echo "📋 COMPONENTI DA STAMPARE:"
echo "1. Telaio (PETG, 48h)"
echo "2. Pieghevole (ABS, 6h)"
echo "3. Box Batteria (PETG, 10h)"
echo "4. Supporto ESP32 (PLA, 3h)"
echo "5. Attacchi Ruota (PETG, 4h)"
echo "6. Parafanghi (TPU, 8h)"
echo "7. Manopole (TPU, 2h)"
echo "8. Pedana (TPU, 4h)"
echo "9. Supporto Motore (PETG, 8h)"
echo "10. Box Display (PLA, 2h)"
echo ""
echo "📊 TOTALE: 127 ore di stampa"
echo "📦 FILAMENTO: 10kg"
echo ""
echo "✅ PRONTO PER INIZIARE!"
echo ""
echo "📖 Consulta: weekly-plan.md per il programma"
