#!/bin/bash
# 🔍 URBAN LAB - Verifica Componenti

echo "🔍 URBAN LAB - VERIFICA COMPONENTI"
echo "=================================="
echo ""

echo "📋 Controlla di avere tutti i componenti:"
echo ""
echo "🔧 STRUTTURA:"
echo "   [ ] Telaio alluminio 120x80x60cm"
echo "   [ ] Pannelli fibra carbonio"
echo "   [ ] Viti e bulloni M3-M8"
echo ""
echo "⚡ ELETTROMAGNETICA:"
echo "   [ ] Bobina Tesla 100kV"
echo "   [ ] 8 Magneti N52"
echo "   [ ] 10 Condensatori 450V"
echo ""
echo "💻 CONTROLLO:"
echo "   [ ] Raspberry Pi 5 8GB"
echo "   [ ] Arduino Mega 2560"
echo "   [ ] Display OLED 7\""
echo ""
echo "🧲 SENSORI:"
echo "   [ ] 4 Sensori Hall A1324"
echo "   [ ] 4 Sensori DS18B20"
echo "   [ ] Cavi e connettori"
echo ""
echo "🔋 ALIMENTAZIONE:"
echo "   [ ] Batteria 48V 100Ah"
echo "   [ ] Inverter 48V→220V"
echo "   [ ] Caricabatterie"
echo ""
echo "🛠️ ATTREZZATURA:"
echo "   [ ] Stazione saldatura"
echo "   [ ] Multimetro"
echo "   [ ] Set cacciaviti"
echo "   [ ] Pinze e tronchesi"
echo ""
echo "🛡️ SICUREZZA:"
echo "   [ ] Guanti isolanti"
echo "   [ ] Occhiali di sicurezza"
echo "   [ ] Estintore"
echo ""
echo "✅ Verifica completata!"
